- name: Ensure users are removed from the system
  hosts: all
  gather_facts: true
  become: true
  vars:
    developers_username:
      - testuser

  tasks:
    - name: Gather current user from environment
      ansible.builtin.set_fact:
        current_user: "{{ ansible_facts['env']['USER'] }}"

    - name: Debug - show current user
      ansible.builtin.debug:
        msg: "Current user is {{ current_user }}"

    - name: Remove users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: false
      loop: "{{ developers_username }}"
      when: item != current_user  # Skip the current primary user
      become: true

    - name: Remove ssh directory
      ansible.builtin.file:
        state: absent
        path: /home/{{ item }}/.ssh
      loop: "{{ developers_username }}"
      when: item != current_user  # Skip the current primary user's .ssh directory
      become: true
