---
- name: Update DNS settings in resolved.conf
  hosts: all
  become: yes

  tasks:
    - name: Append DNS settings to resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        line: "{{ item }}"
        create: yes
      loop:
        - "DNS=10.0.87.4"
        - "FallbackDNS=8.8.8.8"
      notify: Restart systemd-resolved

  handlers:
    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
