---
- name: Update resolv.conf file
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Update resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: ^nameserver
        line: nameserver 10.0.87.4
        line: nameserver 8.8.8.8
        line: nameserver 172.16.200.1
        line: nameserver 172.16.100.1
        state: present
