---
- name: Setup Virtual Display with Dummy Driver on Ubuntu Server
  hosts: ubuntu_server
  become: true
  tasks:

    - name: Install xserver-xorg-video-dummy package
      apt:
        name: xserver-xorg-video-dummy
        state: present
        update_cache: yes

    - name: Create Xorg configuration directory if it doesn't exist
      file:
        path: /etc/X11/xorg.conf.d
        state: directory
        mode: '0755'

    - name: Create Xorg configuration file for dummy display
      copy:
        dest: /etc/X11/xorg.conf.d/10-dummy.conf
        content: |
          Section "Device"
              Identifier  "DummyDevice"
              Driver      "dummy"
          EndSection

          Section "Monitor"
              Identifier  "DummyMonitor"
              HorizSync   31.5-48.5
              VertRefresh 50-70
              Modeline "1920x1080"  148.5  1920 2008 2052 2200  1080 1084 1089 1125  -hsync +vsync
          EndSection

          Section "Screen"
              Identifier "DummyScreen"
              Monitor    "DummyMonitor"
              Device     "DummyDevice"
              DefaultDepth 24
              SubSection "Display"
                  Depth 24
                  Modes "1920x1080"
              EndSubSection
          EndSection

          Section "ServerLayout"
              Identifier "DummyLayout"
              Screen "DummyScreen"
          EndSection
      notify:
        - Restart display manager

  handlers:
    - name: Restart display manager
      systemd:
        name: display-manager
        state: restarted
        enabled: yes
